### ISSUE TITLE
fsevents_to_vm is running but no events are passed to the VM

### ISSUE THREAD

**Issue by mgdesign** [sparkfabrik/sparkdock#12]
Even thou the fsevents_to_vm processes is running on my machine, no events seems to be propagated to the VM.
This is the output of `ps aux | grep fsevents_to_vm` on my macOsx

`marcello          2440   0.0  0.0  2444056    832 s001  S+    2:52PM   0:00.00 grep fsevents_to_vm`

**Comment by mgdesign** [comment]
Running `fsevents_to_vm` from the command line triggers this error

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fsevents_to_vm' (>= 0) among 183 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/fsevents_to_vm:22:in `<main>'
```

This is the output of `ruby -v`
```
> ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
```

Is the reason of the error maybe caused by the use of RVM?
